export default [
  {
    "Naziv kolegija": "Programiranje 1",
    "Kod kolegija": "INB1026",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "4",
    "Semestar": "1.",
    "P": "15",
    "S": "0",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "Ulazne kompetencije: poznavanje osnova rada na računalu.",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Tomislav Volarić, doc.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tomislav.volaric@fpmoz.sum.ba",
    "Asistent": "tomislav.volaric@fpmoz.sum.ba",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tomislav.volaric@fpmoz.sum.ba",
    "Ciljevi kolegija": "Ciljevi kolegija su: Urediti znanja stečena o ovom području u prethodnom obrazovanju. Razumjeti, usvojiti i naučiti proceduru i aktivnosti za rješavanje problema i razvoj programske podrške na računalu. Razumjeti, usvojiti i naučiti osnovni koncept programiranja sa stajališta programskih instrukcija za prihvat podataka, obrade podataka, spremanje i raspodjele rezultata obrade podataka. Razumjeti, usvojiti i naučiti osnovni concept za spremanje i ponovno korištenje podataka.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: \n klasificirati osnovne algoritamske strukture \n klasificirati osnovne tipove grešaka \n identificirati greške u programskom rješenju \n napraviti dijagram toka i pseudokod algoritma \n usporediti osnovne algoritme sortiranja \n napisati programe u programskom jeziku Python \n procijeniti ispravnost programskog rješenja \n vrednovati gotova programska rješenja",
    "Način izvođenja nastave": "predavanja, vježbe, samostalni zadaci, konzultacije",
    "Studentske obveze": `pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, polagati pismeni ispit, polagati usmeni ispit.`,
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, praktični rad, usmeni ispit, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Računalni praktikum 1",
    "Kod kolegija": "INB1033",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1",
    "ECTS vrijednost boda": "3",
    "Semestar": "1.",
    "P": "0",
    "S": "0",
    "V": "45",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Tomislav Volarić, doc.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tomislav.volaric@fpmoz.sum.ba",
    "Asistent": "",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Cilj praktikuma je da se studenti na praktičan način upoznaju sa raznim aspektima suvremene programske i sklopovske tehnologije",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će moći/znati: razlikovati glavne hradverske dijelove računala, sastaviti I rastaviti PC, instalirati operacijskisustav, koristiti MS Word na naprednom novou, koristiti MS Excel na naprednom nivou",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Građa računala - Memorija, U/I sklopovi, CPU, Matične ploče, Mediji, HDD Rastavljanje i sastavljanje PC-a - Svaki student će rastaviti i sastaviti računalo. Operacijski sustavi (ljuska, jezgra, podjela sustava, zadatak OS, uloga u izvođenju procesa, primjer instalacije Windows 10…) Ms Word - Napredne funkcije Ms Worda, Izrada automatske tablice, Automatski popis slika i tablica, Zaglavlje i podnožje dokumenta, Pisanje formula, Ugnježdavanje Excel podataka u Word, Mail merge (skupno pismo) MS Excel - Formule i funckije, Average, sum, min, max, count, countblank, IF funkcija, Povezivanje IF funkcije s drugim funkcijama, Statistički excel, Grupiranje podataka, Histogram, Pivot table…",
    "Način izvođenja nastave": "predavanja, vježbe, samostalni zadaci, konzultacije, praktični rad",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, praktični rad, usmeni ispit, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Matematika 1",
    "Kod kolegija": "INB1018",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "8",
    "Semestar": "1.",
    "P": "45",
    "S": "0",
    "V": "45",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "Studenti studija informatike i cestovnog prometa",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "Dr.sc.Sanja Tipurić Spužević, doc",
    "Kontakt sati/konzultacije": "sanja.spuzevic@fpmoz.sum.ba",
    "E-mail adresa i broj telefona": "",
    "Asistent": "Mila Zovko, v.asist.",
    "Kontakt sati/konzultacije": "mila.zovko@fpmoz.sum.ba>",
    "E-mail adresa i broj telefona": "Prema rasporedu",
    "Ciljevi kolegija": "Intuitivnim prezentiranjem teorije i ilustrativnim primjerima osposobiti studente za praćenje stručnih predmeta i rješavanje praktičnih problema.",
    "Ishodi učenja (opće i specifične kompetencije)": "Uspješan student će nakon položenog kolegija biti osposobljen za: - definirati polja realnih i kompleksnih brojeva - objasniti princip matematičke indukcije - opisati svojstva realnih elementarnih funkcija - primijeniti diferencijalni račun na ispitivanje svojstava realnih funkcija - odrediti neodređeni integral i izračunati određeni integral - primijeniti diferencijalni i integralni račun na probleme u geometriji - analizirati konvergenciju nizova i redova - vješto koristiti matrični račun",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Skupovi brojeva, funkcije, aksiomi polja, supremum, infimum, matematička indukcija (3) 2. Niz i podniz, limes niza u R, Cauchyjev niz, prebrojivost (3) 3. Limes i neprekidnost funkcije, elementarni primjeri (3) 4. Derivacija funkcije i njezino geometrijsko značenje, pravila deriviranja, derivacije elementarnih funkcija, složene i inverzne funkcije, deriviranje implicitno zadane funkcije (6) 5. Derivacije višeg reda, diferencijal funkcije, teoremi diferencijalnog računa, neke primjene derivacija (6) 6. Neodređeni integral, integriranje elementarnih funkcije, osnovne metode integriranja (6) 7. Određeni integral, Newton-Leibnizova formula, nepravi integral, neke primjene određenog integrala (6) 8. Redovi realnih brojeva, konvergencija redova, kriteriji konvergencije redova, Talorovi redovi, Fourierovi redovi (6) 9. Matrice i operacije s njima, determinanta, inverzna matrica, elementarne transformacije nad matricama, rang, sustavi linearnih jednadžbi, Cramerovo pravilo, dekompozicija singularnih vrijednosti (6)",
    "Način izvođenja nastave": "predavanja, vježbe",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "usmeni ispit, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Osnove informatike 1",
    "Kod kolegija": "INB1048",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "8",
    "Semestar": "1.",
    "P": "30",
    "S": "30",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Tonćo Marušić, izv. prof.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tonco.marusic@fpmoz.sum.ba",
    "Asistent": "Željko Marušić, v. asist.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "zeljko.marusic@fpmoz.sum.ba",
    "Ciljevi kolegija": "Ciljevi kolegija su: Ovaj kolegij pruža uvid u sadržaje više kolegija koji se slušaju tijekom studija. Kolegij daje pregled prodručja koje izučava računalna znanost, podjednako u smislu područja istraživanja i primjene. Pored toga cilj je upoznati temeljne matematičke temelje potrebne za razumijevanje rada računala. Kroz kolegij se upoznaju područja: povijest računarstva, podjela računarstva po područjima, arhitektura računala, operacijski sustavi, baze podataka, računalne mreže, arhitektura internetskih aplikacija, računalna grafika i umjetna inteligencija. U praktičnom dijelu kolegija kroz zadatke se usvajaju koncepti: brojevni sustavi, logički sklopovi, obrada teksta, proračunske tablice i baze podataka.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: Opisati povijest razvoja računarstva. Razumjeti podjelu računarstva na područja. Raspravljati o osnovnim konceptima iz područja arhitekture računala, operacijskih sustava, baza podataka, računalnih mreža, arhitekture internetskih aplikacija, računalne grafike i umjetne inteligencije. Primijeniti aplikacije za obradu teksta, proračunske tablice i sustav za upravljanje bazom podataka za rješavanje problema. Prepoznati granice mogućnosti pojedinih područja računarstva.",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Predavanja: Algoritmi i računala kroz vrijeme, Osnovni principi računalne tehnologije, Brojevni sustavi i predstavljanje podataka, Pohrana podataka i problemi kompresije, Arhitektura računala i simulacija računalnih sklopova, Operacijski sustavi, Računalne mreže i internet, Mrežni protokoli i sigurnost, Baze podataka, Računalna grafika, Umjetna inteligencija, Vježbe: Uvod, Brojevni sustavi, Logički sklopovi, Problemski zadaci, Obrada teksta, Proračunske tablice, Baze podataka, Problemski zadaci",
    "Način izvođenja nastave": "predavanja, vježbe, seminari, samostalni zadaci, konzultacije",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, pisati seminarski rad, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastae, aktivnosti u nastavi, seminarski rad, praktični rad, usmeni ispit, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Engleski jezik 1",
    "Kod kolegija": "OPB1012",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "2",
    "Semestar": "1.",
    "P": "15",
    "S": "0",
    "V": "15",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "Studenti prve godine studija Matematike",
    "Vrijeme održavanja nastave": "Prema semestralnom rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Ivana Grbavac, izv.prof",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "ivana.grbavac@ff.sum.ba, 063 377 224",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Osposobiti studente za samostalno praćenje i razumijevanje pisanog i govornog engleskog jezika; ispravno korištenje gramatičkih konstrukcija engleskog jezika; obogaćivanje vokabulara različitim vrstama tekstova.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon odslušanog kolegija studenti će znati i moći: ispravno koristiti engleska glagolska vremena, točno koristiti pasivne konstrukcije u engleskom jeziku, samostalno pratiti i razumijeti elemente pisanog i govornog engleskog jezika, razgovarati na engleskom jeziku o stručnim temama",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Gramatičke vježbe u kombinaciji s vježbama čitanja i prevođenja tekstova izvan struke kao i stručnih tekstova. Predavanja se kombiniraju s komunikativnim pristupom u nastavi  - potrebno je aktivno sudjelovanje u raspravama i grupnom radu. Korištenje audio/video/web-materijala. Studente se potiče na korištenje fakultetske računalne opreme prilikom držanja prezentacija. Obrađuju se temeljne gramatičke cjeline (sustav engleskih glagolskih vremena, passiv, itd.)",
    "Način izvođenja nastave": "predavanja, seminari, konzultacije",
    "Studentske obveze": "redovito pohađati nastavu, aktivno sudjelovati u nastavi napisati koherentan seminarski rad na zadanu temu, pisati završni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, seminarski rad, pismeni ispit",
  },
  {
    "Naziv kolegija": "Tjelesna i zdravstvena kultura 1",
    "Kod kolegija": "INB1071",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "1",
    "Semestar": "1.",
    "P": "0",
    "S": "30",
    "V": "0",
    "Status kolegija": "obvezni",
    "Preduvjeti": "Uredno pohađanje vježbi",
    "Usporedni uvjeti": "Seminarski rad",
    "Pristup kolegiju": "Studenti 1. i 2. godine fakulteta",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Ivan Kvesić, doc.",
    "Kontakt sati/konzultacije": "Srijeda, 12:00 sati, kabinet 113a, Rodoč",
    "E-mail adresa i broj telefona": "kvesic, ivan@fpmoz.sum.ba, +387 (0)63 479 799",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Ciljevi ovog kolegija su: Stjecanje općih kompetencija po pitanju poznavanja utjecaja kinezioloških aktivnosti na stupanj zdravlja. Studente upoznati sa općim procesom vježbanja kao i posljedicama djelovanja tih procesa na ljudski organizam s posebnim osvrtom na očuvanje zdravlja koje postižu kineziološkim procesima. Upoznati studente s načinima rješavanja problematike vezane uz upravljanje procesom vježbanja. Osposobiti ih i potaknuti na samostalan rad i posvijestiti im važnost bavljenja sportom u svakodnevnom životu.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon što odslušaju i polože ovaj kolegij, studenti će znati / moći i biti: osposobljeni i potaknuti na samostalan rad i posviješteni na važnost baljenja sportom u svakodnevnom životu, prepoznati potrebu i važnost redovite tjelovježbe u svrhu očuvanja zdravlja i poboljšanja kvalitete života, Kreirati aktivni odmor (aktivna stanka između učenja, tijekom slobodnog vremena), prezentirati tolerantnost, radne navike i samodisciplinu, primijeniti nekoliko vježbi zagrijavanja za pojedinu kineziološku aktivnost, primijeniti neke vježbe istezanja za pojedinu kineziološku aktivnost, objasniti osnove o utjecaju redovitog vježbanja na zdravlje, osmisliti tjelovježbu u svrhu aktivnog provođenja slobodnog vremena, kreirati uvodni i završni dio sata (treninga)",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Ponuđeni sadržaji studentima koje mogu birati kao svoje aktivnosti: aerobik, fittnes, plesovi (plesne strukture), nogomet, košarka, dbojka, livanje, vaterpolo, stolni tenis, tenis, samoobrana, aktivnosti na trim stazi na Bijelom Brijegu, izleti-pješačke ture, organizacija natjecanja u više sportova unutar Fakulteta, sportska suradnja ekipa sa drugim fakultetima u regiji",
    "Način izvođenja nastave": "vježbe, seminari, samostalni zadaci",
    "Studentske obveze": "Obavezno pohađanje vježbi",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, seminarski rad",
  },
  {
    "Naziv kolegija": "Filozofija znanosti",
    "Kod kolegija": "INB1082",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "2",
    "Semestar": "1.",
    "P": "15",
    "S": "0",
    "V": "15",
    "Status kolegija": "izborni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Zoran Primorac, red. prof.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "zoran.primorac@fpmoz.sum.ba",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Ciljevi kolegija su: steći sposobnost prepoznavanja i opisivanja filozofskih pitanja u znanstvenoj spoznaji",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: napraviti logičku analizu znanstvenih tekstova.",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": " Kolegij obuhvaća tri dijela. Prvi je dio uvodnog karaktera i posvećen je općenitom filozofsko-logičkom i metodološkom obrazovanju. Drugi i treći usmjereni su prema izabranim pitanjima filozofije znanosti. U prvom se dijelu uvode osnovni logički i metodološki pojmovi. U drugom dijelu razmatraju se izabrani problemi filozofije znanosti uz tumačenje izvornih tekstova. Odnos spoznaje i jezika tematizira se na Wittgensteinovom Tractatus-u. Proučava se Carnapov (empirijski) kriterij smislenosti. Analizira se Popperov prikaz znanstvene metode. Razlike između znanosti o čovjeku i znanosti o prirodi analiziraju se obzirom na razliku u vrsti objašnjenja (Von Wright) i obzirom na jezik (Davidson). Pitanje ograničenja spoznaje istražuje se u filozofskom tumačenju Gödelovih metateorijskih rezultata. U trećem, kraćem dijelu analizira se pitanje promjene teorije u okviru Kuhnove filozofije povijesti znanosti te u okviru suvremenih formalnih teorija.",
    "Način izvođenja nastave": "predavanja, vježbe",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, usmeni ispit, pismeni ispit",
  },
  {
    "Naziv kolegija": "Novi mediji u odgoju i obrazovanju",
    "Kod kolegija": "PKB3052",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "2",
    "Semestar": "1.",
    "P": "30",
    "S": "0",
    "V": "30",
    "Status kolegija": "izborni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "Studenti pedagogije",
    "Vrijeme održavanja nastave": "Sukladno rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Antea Čilić, doc.",
    "Kontakt sati/konzultacije": "Sukladno rasporedu",
    "E-mail adresa i broj telefona": "antea.cilic@fpmoz.sum.ba",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Upoznati studente s temeljnim spoznajama iz područja medijske pedagogije i didaktike. Steći znanja o vrstama i ulozi medija i mogućnostima korištenja medija u nastavnom procesu..",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog ispita studenti će moći: definirati i razumjeti temeljne spoznaje iz područja primjene, utjecaja i važnosti korištenja medija u odgoju i obrazovanju, definirati, razlikovati i vrednovati medije u odgojno-obrazovnom procesu s obzirom na izbor, funkciju i klasifikaciju medija te njihovu primjenu u nastavnom procesu i slobodnom vremenu, vrednovati prema glavnim značajkama specifičnosti pojedinih medija, analizirati i vrednovati specifične medije s obzirom na njihovu odgojnu i obrazovnu ulogu, kvalitetu i utjecaj na mlade",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Mediji u obrazovanju, medijska pedagogija E-učenje, područja medija u odgoju i obrazovanju",
    "Način izvođenja nastave": "predavanja, vježbe, seminari, samostalni zadaci, konzultacije",
    "Studentske obveze": "prisustvovati nastavi, izraditi i izložiti radni zadatak, polagati pismeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, seminarski rad, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Rješavanje problemskih zadataka programiranjem",
    "Kod kolegija": "INB2116",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1",
    "ECTS vrijednost boda": "6",
    "Semestar": "2.",
    "P": "30",
    "S": "0",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "Programiranje 1",
    "Usporedni uvjeti": "Ulazne kompetencije: programiranje u Python-u",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Goran Kraljević, doc.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "goran.kraljevic@fpmoz.sum.ba",
    "Asistent": "Emil Brajković v.asist.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "emil.brajkovic@fpmoz.sum.ba",
    "Ciljevi kolegija": "Ciljevi kolegija su: Riješiti problemski zadatak algoritamskim pristupom. Razumjeti i formalizirati problemski zadatak. Oblikovati i implementirati algoritamsko rješenje. Testirati i izmjeriti algoritamsko rješenje.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: analizirati problemski zadatak, formulirati algoritamsko rješenje problemskog zadatka, evaluirati algoritamsko rješenje, implementirati algoritam u programskom jeziku Python",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": `Uvodno predavanje: nastavnici, obaveze studenata, elementi tekućeg praćenja, ispit, ocjena, predstavljanje ciljeva kolegija, literatura; Varijabla, brojčani tip i operatori, logički tip i operatori, grananje, uvjetna petlja, funkcija (3).
    String i metode nad stringom, bezuvjetna petlja, operator sadržavanja (3).
    Lista i metode nad listom, operatori liste, generatori, rezanje liste, shvaćanje liste, sortiranje, prilagođeno sortiranje, nepromjenjive liste (3)
    Matrica kao lista koja sadrži liste, inicijalizacija matrice, promjena matrice, ispis materice, Rječnik, metode rječnika, brisanje varijabli (3).
    Rekurzija, faktorijela, rekurzivno generiranje niza, rekurzivno permutiranje niza, dubinsko pretraživanje pomoću rekurzije (3).
    Kolokvij (3).
    Rješavanje lakših problemskih zadataka s natjecanja (3).
    Rješavanje lakših problemskih zadataka s natjecanja (3).
    Rješavanje lakših problemskih zadataka s natjecanja (3).
    Kolokvij (3).
    Timsko rješavanje težih problemskih zadataka s natjecanja (3).
    Skupovi i metode na skupovima, timsko rješavanje težih problemskih zadataka s natjecanja (3).
    Timsko rješavanje težih problemskih zadataka s natjecanja (3).
    Timsko rješavanje težih problemskih zadataka s natjecanja (3).
    Kolokvij (3).
`,
    "Način izvođenja nastave": "predavanja, vježbe",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, pismeni ispit, kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "Programiranje 2",
    "Kod kolegija": "INB2028",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "8",
    "Semestar": "2.",
    "P": "30",
    "S": "30",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "poznavanje osnova rada na računalu, poznavanje osnovnih algoritama",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Marko Rosić, red. prof.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "marko.rosic@fpmoz.sum.ba",
    "Asistent": "Emil Brajković, v. asist.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "emil.brajkovic@fpmoz.sum.ba",
    "Ciljevi kolegija": "Ciljevi kolegija su: Urediti znanja stečena o ovom području u prethodnom obrazovanju. Razumjeti, usvojiti i naučiti proceduru i aktivnosti za rješavanje problema i razvoj programske podrške na računalu. Razumjeti, usvojiti i naučiti osnovne koncepte objektno- orijentiranog programiranja. Razumjeti, usvojiti i naučiti osnovni koncept za spremanje i ponovno korištenje podataka.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: klasificirati tipove podataka, klasificirati osnovne algoritamske strukture, klasificirati osnovne tipove grešaka, identificirati i ukloniti greške u programskom rješenju, kreirati konzolske i grafičke aplikacije, napisati vlastite tipove podataka, napisati klase, razlikovati osnovne strukture podataka",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": `Predavanja:
    Pregled kolegija, uvod u programski jezik C# (2).
    Izrada programske podrške, integrirana razvojna okolina, primjeri okruženja, instalacija okruženja za rad (2).
    tipovi podataka u C# (jednostavni: tekstualni i brojčani), algoritamske strukture odluke i petlje (2).
    Složenije strukture podataka: nizovi (jednodimenzionalni i dvodimenzionalni), strukture (struct) (2).
    rekurzije, top-down metoda na primjeru (2).
    testiranje programske podrške, vrste pogrešaka, prepoznavanje i uklanjanje, rješavanje primjera kolokvija (2).
    grafičko korisničko sučelje, uvod u .NET, oblikovanje osnovnih GUI elemenata, kontrole (2).
    okruženje za izradu GUI aplikacije (2).
    Klase i objekti u C# (2).
    Elementi naprednih grafičkih aplikacija (2).
    Nizovi, liste i kolekcije (2).
    Tokovi podataka i datoteke (2).
    Napredni sustavi pohrane (binarne datoteke) (2).
    Primjeri zadataka i priprema za 2. kolokvij (2).
    Analiza kolokvija (2).
    Vježbe:
    Ulazni test na računalu (2).
    Osnovne I/O naredbe (2).
    Slučajni brojevi, algoritmi za traženje minimuma, maksimuma, prostih brojeva (2).
    Nizovi, unos ispis niza, nizovi riječi, matrice (dvodimenzionalni nizovi), metode (2).
    rekurzije (2).
    ponavljanje za kolokvij (2).
    Kolokvij 1 (2).
    Izrada jednostavne GUI (2).
    Unos i čitanje podataka iz kontrola combo, list, … (2).
    Rad s više obrazaca, izbornik (2).
    Upotreba i kreiranje klasa, instanci, konstruktora, tipova, svojstava (2).
    Upotreba nizova i lista (2).
    Datoteke i tokovi podataka (2).
    ponavljanje za 2. kolokvij (2).
    Kolokvij 2. (2).
`,
    "Način izvođenja nastave": "predavanja, vježbe, samostalni zadaci",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, pisati seminarski rad, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, seminarski rad, praktični rad, usmeni ispit, pismeni ispit, kontinuirana znanja",
  },
  {
    "Naziv kolegija": "Računalni praktikum 2",
    "Kod kolegija": "IMB2503",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "3",
    "Semestar": "2.",
    "P": "15",
    "S": "0",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Tomislav Volarić",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tomislav.volaric@fpmoz.sum.ba",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Stjecanje znanja o računalnim mrežama (prijenos podataka, podjela računalnim mreža po različitim kriterijima). Stjecanje znanja o internetu (povijest, organizacija, arhitektura, protokoli i usluge). Poznavanje internet usluga i odgovarajućih protokola aplikacijskog sloja. Upoznati se s različitim vrstama adresa na internetu. Upoznati se s različitim tehnologijama pristupa internetu. Poznavanje sigurnosnih problema na internetu i načina zaštite. Na vježbama savladati korištenje internet aplikacija. Izrađivati i oblikovati web stranice.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: 1. Nabrojati različite podjele računalnih mreža i objasniti razlike, razlikovati usluge i protokole na internetu po namjeni. 2. Nabrojati i objasniti vrste adresa na Internet. 3. Nabrojati i objasniti razliku između tehnologija pristupa internetu. 4. Nabrojati sigurnosne prijetnje na internetu i objasniti razlike. 5. Izrađivati HTML datoteke i primjenjivati oblikovanje CSSom. 6. Postavljati web stranice na poslužitelj. 7. Koristiti aplikacija u oblaku (eng. cloud computing)",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": `1. Računalne mreže (prijenos podataka, podjela), Internet (povijest i razvoj) 
    2. Internet usluge (načini korištenja, usluge, protokoli) 
    3. TCP/IP model (osnovno), adresiranje na internetu 
    4. Pristup internetu (tehnologije koje se koriste, brzina prijenosa podataka) 
    5. Sigurnost na internetu (vrste prijetnji i kako se štititi) 
    6. HTML 
    7. Postavljanje na poslužitelj
    8. Aplikacije na internetu (računarstvo u oblaku) 3 sata; CSS 
    `,
    "Način izvođenja nastave": "predavanja, vježbe",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, usmeni ispit, pismeni ispit",
  },
  {
    "Naziv kolegija": "Matematika 2",
    "Kod kolegija": "INB2048",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "8",
    "Semestar": "2.",
    "P": "45",
    "S": "0",
    "V": "45",
    "Status kolegija": "obvezni",
    "Preduvjeti": "Odslušan kolegij Matematika 1",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Sanja Tipurić Spužević, doc.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "sanja.spuzevic@fpmoz.sum.ba",
    "Asistent": "Mila Zovko, v. asist.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "mila.zovko@fpmoz.sum.ba",
    "Ciljevi kolegija": "Ciljevi kolegija su: Intuitivnim prezentiranjem teorije i ilustrativnim primjerima osposobiti studente za praćenje stručnih predmeta i rješavanje praktičnih problema.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon položenog kolegija student će znati/moći: Geometrijski i analitički prikazati vektor te koristiti skalarni i vektorski produkt u analitičkoj prezentaciji ravnina i pravaca; geometrijski interpretirati jednadžbe pravca, ravnine te jednostavnijih konika i kvadrika; izračunati limes i derivaciju funkcija 2 i 3 varijable; primijeniti diferencijalni račun u rješavanju optimizacijskih problema; primijeniti integralni račun za određivanje površina likova i volumena tijela;prepoznati i riješiti različite ODJ 1. reda i LDJ n-tog reda",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": `Klasična algebra vektora (4)
    Analitička geometrija ravnine i pravca (4)
    Ravninski i prostorni koordinatni sustavi (3)
    Krivulje i plohe drugog reda (3)
    Skalarne funkcije više varijabli (2)
    Limes i neprekidnost funkcije više varijabli (2)
    Parcijalna derivacija (3)
    Diferencijal i tangencijalna ravnina (3)
    Lokalni ekstrem funkcije više varijabli (4)
    Uvjetni ekstrem i Lagrangeov multiplikator (3)
    Dvostruki i trostruki integral (3)
    Fubinijev teorem, zamjena varijabli (3)
    Primjene dvostrukog i trostrukog integrala (2)
    ODJ 1. reda (3)
    LDJ 2. reda (3)
    `,
    "Način izvođenja nastave": "predavanja, vježbe, samostalni zadaci, konzultacije",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, pisati kolokvije, polagati pismeni ispit, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, pismeni ispit, usmeni ispit, kontinuirana provjera znanja"
  },
  {
    "Naziv kolegija": "Engleski jezik 2",
    "Kod kolegija": "OPB2092",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "",
    "Semestar": "2.",
    "P": "15",
    "S": "0",
    "V": "15",
    "Status kolegija": "obvezni",
    "Preduvjeti": "Odslušan Engleski jezik 1",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "Studenti prve godine studija Matematika",
    "Vrijeme održavanja nastave": "Prema semestralnom rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Ivana Grbavac, izv. prof.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "ivana.grbavac@ff.sum.ba, 063 377 224",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Osposobiti studente za samostalno praćenje i razumijevanje pisanog i govornog engleskog jezika; ispravno korištenje gramatičkih konstrukcija engleskog jezika; obogaćivanje vokabulara različitim vrstama tekstova.",
    "Ishodi učenja (opće i specifične kompetencije)": "Nakon odslušanog kolegija studenti će znati i moći: ispravno koristiti vrste riječi u engleskom jeziku, točno koristititi složenije gramatičke konstrukcije, samostalno pratiti i razumijeti elemente pisanog i govornog engleskog jezika, razgovarati na engleskom jeziku o stručnim temama",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Gramatičke vježbe u kombinaciji s vježbama čitanja i prevođenja tekstova izvan struke kao i stručnih tekstova. Predavanja se kombiniraju s komunikativnim pristupom u nastavi  - potrebno je aktivno sudjelovanje u raspravama i grupnom radu. Korištenje audio/video/web-materijala. Studente se potiče na korištenje fakultetske računalne opreme prilikom držanja prezentacija. Obrađuju se složenije gramatičke cjeline (vrste riječi, if-rečenice, slaganje vremena itd.)",
    "Način izvođenja nastave": "predavanja, seminari, konzultacije",
    "Studentske obveze": "redovito pohađati nastavu, aktivno sudjelovati u nastavi, napisati koherentan seminarski rad na zadanu temu, pisati završni ispit",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, seminarski rad, pismeni ispit",
  },
  {
    "Naziv kolegija": "Tjelesna i zdravstvena kultura 2",
    "Kod kolegija": "OPB2031",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "1",
    "Semestar": "2.",
    "P": "0",
    "S": "30",
    "V": "0",
    "Status kolegija": "obvezni",
    "Preduvjeti": "Uredno pohađanje vježbi",
    "Usporedni uvjeti": "Seminarski rad",
    "Pristup kolegiju": "Studneti 1. i 2. godine",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Ivan Kvesić, doc.",
    "Kontakt sati/konzultacije": "Srijeda, 12.00 sati, kabinet 113a, Rodoč",
    "E-mail adresa i broj telefona": "kvesic.ivan@fpmoz.sum.ba, +387 (0)63 479 799",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "Ciljevi ovog kolegija su: Stjecanje općih kompetencija po pitanju poznavanja utjecaja kinezioloških aktivnosti na stupanj zdravlja. Studente upoznati sa općim procesom vježbanja kao i posljedicama djelovanja tih procesa na ljudski organizam s posebnim osvrtom na očuvanje zdravlja koje postižu kineziološkim procesima. Upoznati studente s načinima rješavanja problematike vezane uz upravljanje procesom vježbanja. Osposobiti ih i potaknuti na samostalan rad i posvijestiti im važnost baljenja sportom u svakodnevnom životu.",
    "Ishodi učenja (opće i specifične kompetencije)": `
    Nakon što odslušaju i polože ovaj kolegij, studenti će znati / moći i biti:
    Osposobljeni i potaknuti na samostalan rad i posviješteni na važnost baljenja sportom u svakodnevnom životu.
    Prepoznati potrebu i važnost redovite tjelovježbe u svrhu očuvanja zdravlja i poboljšanja kvalitete života.
    Kreirati aktivni odmor (aktivna stanka između učenja, tijekom slobodnog vremena).
    Prezentirati tolerantnost, radne navike i samodisciplinu.
    Primijeniti nekoliko vježbi zagrijavanja za pojedinu kineziološku aktivnost.
    Primijeniti neke vježbe istezanja za pojedinu kineziološku aktivnost.
    Objasniti osnove o utjecaju redovitog vježbanja na zdravlje.
    Osmisliti tjelovježbu u svrhu aktivnog provođenja slobodnog vremena.
    Kreirati uvodni i završni dio sata (treninga).
    `,
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Ponuđeni sadržaji studentima koje mogu birati kao svoje aktivnosti: Aerobik, Fittnes, Plesovi (plesne strukture), Nogomet, Košarka, Odbojka, Plivanje, Vaterpolo, Stolni tenis, Tenis, Samoobrana, Aktivnosti na trim stazi na Bijelom Brijegu, Izleti-pješačke ture, Organizacija natjecanja u više sportova unutar Fakulteta, Sportska suradnja ekipa sa drugim fakultetima u regiji",
    "Način izvođenja nastave": "vježbe seminari, samostalni zadaci, ",
    "Studentske obveze": "Obavezno pohađanje vježbi",
    "Praćenje i ocjenjivanje studenta": "pohađanje nastave, aktivnosti u nastavi, seminarski rad",
  },
  {
    "Naziv kolegija": "Informatički projekt 1",
    "Kod kolegija": "INB2132",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Prvi ciklus",
    "Godina studija": "1.",
    "ECTS vrijednost boda": "2",
    "Semestar": "2.",
    "P": "0",
    "S": "0",
    "V": "30",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "Prema rasporedu",
    "Nositelj kolegija/nastavnik": "dr. sc. Tomislav Volarić, doc.",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "tomislav.volaric@fpmoz.sum.ba",
    "Asistent": "Hrvoje Ljubić. asistent",
    "Kontakt sati/konzultacije": "Prema rasporedu",
    "E-mail adresa i broj telefona": "hrvoje.ljubic@fpmoz.sum.ba",
    "Ciljevi kolegija": "Primijeniti stečena znanja i vještine pri rješavanju konkretnomg problema",
    "Ishodi učenja (opće i specifične kompetencije)": `Nakon položenog kolegija student će moći:
    1. Definirati problem sukladno pravilima struke. 
    2. Samostalno riješiti praktični problem/zadatak. 
    3. primjeniti usvojena znanja i opće kompetencije stečene tijekom prve godine studija. 
    4. Primijeniti usvojena znanja i specifične kompetencije pripadnog
    predmeta (Programiranje 1, Programiranje 2, Osnove informatike, Računalni praktikum 2, Rješavanje problemskih zadataka programiranjem)
    `,
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "Student po uputama nastavnika samostalno radi informatički projektni zadatak. Pručavanje načina izrade i specifikacije informatičkog projekta. Praktični rad. Priprema prezentacije. Obrana projektnog zadatka.",
    "Način izvođenja nastave": "vježbe, samostalni zadatci, konzultacije, seminarski rad",
    "Studentske obveze": "pohađati nastavu i sudjelovati u nastavnome procesu, polagati usmeni ispit",
    "Praćenje i ocjenjivanje studenta": "kontinuirana provjera znanja",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },
  {
    "Naziv kolegija": "",
    "Kod kolegija": "",
    "Studijski program": "Studij Informatike",
    "Ciklus": "Preddiplomski sveučilišni studij",
    "Godina studija": "1",
    "ECTS vrijednost boda": "",
    "Semestar": "",
    "P": "",
    "S": "",
    "V": "",
    "Status kolegija": "obvezni",
    "Preduvjeti": "",
    "Usporedni uvjeti": "",
    "Pristup kolegiju": "",
    "Vrijeme održavanja nastave": "",
    "Nositelj kolegija/nastavnik": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Asistent": "",
    "Kontakt sati/konzultacije": "",
    "E-mail adresa i broj telefona": "",
    "Ciljevi kolegija": "",
    "Ishodi učenja (opće i specifične kompetencije)": "",
    "Sadržaj silabusa/izvedbenog plana (ukratko)": "",
    "Način izvođenja nastave": "",
    "Studentske obveze": "",
    "Praćenje i ocjenjivanje studenta": "",
  },









  {
    "Naziv predmeta": "Računalni praktikum 1",
    "Nositelj predmeta": "",
    "Predavanja": "0",
    "Seminar": "0",
    "Vježbe": "45",
    "Status predmeta": "obvezni",
    "Godina studija u kojoj se izvodi predmet": "1",
    "ECTS bodovi": "3",
    "Ciljevi predmeta": "",
    "Uvjeti za upis predmeta": "Nema uvjeta",
    "Ishodi učenja (kompetencije)": `Nakon položenog kolegija student će moći/znati:
    -razlikovati glavne hradverske dijelove računala
    -sastaviti I rastaviti PC
    -instalirati operacijskisustav
    -koristiti MS Word na naprednom novou
    -koristiti MS Excel na naprednom nivou
    `,
    "Sadržaj predmeta": `Građa računala - Memorija, U/I sklopovi, CPU, Matične ploče, Mediji, HDD
    Rastavljanje i sastavljanje PC-a - Svaki student će rastaviti i sastaviti računalo. Operacijski sustavi (ljuska, jezgra, podjela sustava, zadatak OS, uloga u izvođenju procesa, primjer instalacije Windows 10…)`,
    "Način izvođenja nastave": "Predavanja, vježbe, seminari, samostalni zadaci, konzultacije, mentorski rad, terenska nastava, ostalo",
    "Obveze studenata": `
    - pohađati nastavu i sudjelovati u nastavnome procesu.
    - pisati kolokvije. 
    -	polagati pismeni ispit.
    -	polagati usmeni ispit.
    `,
    "ECTS bodovi dodijeljeni na osnovu obveza studenata": "3",
    "Podatci o ocjenjivanju i bodovanju studenata tijekom nastave i na završnom ispitu": "",
    "Obvezna literatura": `Originalni priručnici za korištenje programskih paketa odnosno alata.
    Interna skripta kolegija.
    `,
    "Dopunska literatura": `PRIMIJENJENA STATISTIKA 
    u MS Excelu, Milan PAPIĆ, Naklada ZORO
    `,
    "Jezik poduke i mogućnost praćenja na drugim jezicima": "Hrvatski jezik",
  },
  {
    "Naziv predmeta": "Opća Pedagogija",
    "Nositelj predmeta": "Dr. sc. Sonja Kovačević, doc.",
    "Predavanja": "30",
    "Seminar": "0",
    "Vježbe": "30",
    "Status predmeta": "obvezni",
    "Godina studija u kojoj se izvodi predmet": "1",
    "ECTS bodovi": "4 ECTS",
    "Ciljevi predmeta": "Ovladavanje osnovnim znanjima iz područja pedagoške teorije i prakse potrebnima za uspješnu organizaciju i provođenje pedagoških aktivnosti i pedagoških procesa u odgojno-obrazovnoj praksi. Spoznati razvojne tendencije alternativnih pedagoških teorija i prakse; spoznati osnovne karakteristike i razvoj školskih sustava.",
    "Uvjeti za upis predmeta": "Nema uvjeta",
    "Ishodi učenja (kompetencije)":
      "-sposobnost misaonog operiranja (indukcija, analiza, sinteza, komparacija, evaluacija…);- analiziranje složenosti fenomena odgoja;- sposobnost primjene ideja u analizi prakse. Od specifičnih kompetencija, očekuje se da studenti mogu:- opisati, definirati i objasniti fenomen odgoja;- analizirati fenomen odgoja na primjerima i slučajevima;- oblikovati i izloţiti ideje, sudjelovati u polemikama i dijalozima.",
    "Sadržaj predmeta":
      "Predavanja. Pedagogija kao znanost;predmet pedagogije, zadaci pedagogije,sustav pedagogijskih znanosti,metode istraživanja u pedagogiji. Antroploške osnove odgoja.Temeljni pojmovi u pedagogiji;osnovne kategorije pedagogije.Struktura odgojnog procesa.Pedagoške koncepcije prakse-odgojno.obrazovne filozofije.Pregled razvoja pedagoških ideja.Odgojno-obrazovna komunikacija. Struktura i dinamika odgojno-obrazovne skupine Obrazovni sustavi –školski sustav u Republici BIH.Seminar.  Analiza i rasprava o pedagoškim problemima obradom sadržaja iz pojedinih izvora pedagoške literature i pedagoške prakse.",
    "Način izvođenja nastave":
      "Program se realizira na predavanjima i seminarima u kojima sudjeluju svi studenti. Tjedne, individualne i grupne konzultacije.",
    "Obveze studenata": "",
    "ECTS bodovi dodijeljeni na osnovu obveza studenata":
      "Udio aktivnosti u ECTS bodovima:\nNastava\nBilješke predavanja\nZadaće s predavanja - 0.5\nSeminarski rad\nPisani rad\nIzlaganje i PPT - 0.5\nSutdij literature (pročitati 5 knjiga - izborna literatura) - 1\n Kolokvij I - 1\nZavršni ispit - 1",
    "Podatci o ocjenjivanju i bodovanju studenata tijekom nastave i na završnom ispitu":
      "Udio aktivnosti u ECTS bodovima:\nNastava\nBilješke predavanja\nZadaće s predavanja - 0.5, 10\nSeminarski rad\nPisani rad\nIzlaganje i PPT - 0.5, 29\nSutdij literature (pročitati 5 knjiga - izborna literatura) - 1, 20\n Kolokvij I - 1, 21\nZavršni ispit - 1, 21",
    "Obvezna literatura": "1. Mušanović M.,Lukaš M. (2011.).Osnove pedagogije, HFD, Rijeka\n2.	Bratanić M. Mikropedagogija, Zagreb 1990, Školska knjiga\n3.	Bratanić, M. (2002). Paradoks odgoja. II izdanje, Hrvatska sveučilišna naklada, Zagreb",
    "Dopunska literatura": "4.	Giesecke, H.(1993), Uvod u pedagogiju, Zagreb Educa\n5. Gudjons, H.(1994), Pedagogija - temeljna znanja, Zagreb, Educa\n6, Konig, E., Zedler, P. (2000.). Teorije znanosti o odgoju, Educa, Zagreb.",
    "Jezik poduke i mogućnost praćenja na drugim jezicima": "Hrvatski jezik",
  },
  {
    "Naziv predmeta": "Didaktika",
    "Nositelj predmeta": "dr. sc. Mario Vasilj, izv. prof.",
    "Predavanja": "30",
    "Seminar": "0",
    "Vježbe": "0",
    "Status predmeta": "obvezni",
    "Godina studija u kojoj se izvodi predmet": "1",
    "ECTS bodovi": "4 ECTS",
    "Ciljevi predmeta": "Upoznati studente s osnovnim didaktičkim spoznajama o nastavi i obrazovanju; demonstrirati suvremene metode i strategije rada u nastavi, te razvijati sposobnosti za njihovu efikasnu primjenu; razvijati kompetencije za kritičko propitivanje recentne nastavne prakse u nas; osposobljavati studente za organizaciju nastave u kojoj dominiraju strategije aktivnog učenja",
    "Uvjeti za upis predmeta": "Položen ispit iz Osnova pedagogije",
    "Ishodi učenja (kompetencije)": "Prorada teorijskih sadržaja i rasprava o didaktičkim problemima,rad u malim skupinama, izrada eseja, i sl. Samostalna proučavanja didaktičke literature, Internet, diskusije, konzultacije",
    "Sadržaj predmeta": "Didaktika – teorija obrazovanja i nastave. Osnovni pojmovi didaktike. Nastava- ciljevi i zadaci. Zadaci odgoja i obrazovanja (Taksonomija)- Bloom ;Planiranje i programiranje nastave; Nastavni plan i program; Teorijsko-metodološki pristupi izradi nastavnih planova i programa; Artikulacija (strukturiranje) i faze nastavnog procesa; Pripremanje  nastavnika i učenika za nastavu,ostvarivanje nastavnog procesa; Evaluacija u procesu nastave i učenja; Principi u procesu nastave i učenja; Pojam i klasifikacija metoda nastave i učenja; Oblici (forme) rada u nastavi i učenju; Mediji u nastavi i učenju",
    "Način izvođenja nastave": "Program se realizira na predavanjima, seminarima i konzultacijama. Seminari se organiziraju kao aktivne studentske radionice u kojima se izrađuju vježbe i kritički razmatraju odabrane teme iz didaktike.",
    "Obveze studenata": "Redovito pohađanje nastave. Seminari se organiziraju kao aktivne studentske radionice u kojima se izrađuju vježbe i kritički razmatraju odabrane teme iz didaktike",
    "ECTS bodovi dodijeljeni na osnovu obveza studenata": "Seminar 1 ETSC, aktivnost  na nastavi 1 ETSC, pohađanje nastave 2 ECTS",
    "Podatci o ocjenjivanju i bodovanju studenata tijekom nastave i na završnom ispitu": "Nakon odslušanih predavanja i ispunjenih seminarskih obveza kandidati pristupaju polaganju pismenog i/ili usmenog ispita.Na konačnu ocjenu utječe i kvaliteta kritičkog razmatranja jednog od izvora iz popisa dopunske literature.",
    "Obvezna literatura": "Bognar, L., Matijević, M. (2002.). Didaktika, Zagreb: Školska knjiga.\n2. Klafki, W. i dr. (1992,). Didaktičke teorije, Zagreb: Educa.\n3. Kyriacou, C. (1995.). Temeljna nastavna umijeća, Zagreb:Educa.\n4. Poljak, V. (1991.). Didaktika, Zagreb: Školska knjiga",
    "Dopunska literatura": "1. Bežen, A. i dr. (1991.). Osnove didaktike, Zagreb: Školske novine.\n2. Jelavić, F. (1998.). Didaktika, Jastrebarsko: Naklada Slap.\n3. March, J.C. (1994.). Kurikulum, Zagreb: Educa.\n4. Matijević, M. (2001.). Alternativne škole, Zagreb: Tipex.\n5. Matijević, M. (2004.). Ocjenjivanje u osnovnoj školi, Zagreb: Tipex.",
    "Jezik poduke i mogućnost praćenja na drugim jezicima": "Hrvatski jezik",
  }
]