export default [
    [
        {
            "Redni broj": "1.",
            "Kod": "INB1018",
            "Naziv kolegija": "Matematika 1",
            "P": "45",
            "S": "0",
            "V": "45",
            "Status kolegija": "A",
            "ECTS bodovi": "8",
            "Nastavnik/asistent": "dr. sc. Sanja Tipurić Spužević, doc. Mila Zovko, viši asistent"
          },
          {
            "Redni broj": "2.",
            "Kod": "INB1026",
            "Naziv kolegija": "Programiranje 1",
            "P": "15",
            "S": "30",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc. Emil Brajković, v.asist."
          },
          {
            "Redni broj": "3.",
            "Kod": "INB1033",
            "Naziv kolegija": "Računalni praktikum 1",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "3",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc Hrvoje Ljubić. asistent"
          },
          {
            "Redni broj": "4.",
            "Kod": "INB1048",
            "Naziv kolegija": "Osnove informatike",
            "P": "30",
            "S": "30",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "8",
            "Nastavnik/asistent": "dr. sc.  Tonćo Marušić, doc. dr. sc. Željko Marušić, v. asist."
          },
          {
            "Redni broj": "5.",
            "Kod": "",
            "Naziv kolegija": "Izborni kolegij",
            "P": "15",
            "S": "0",
            "V": "15",
            "Status kolegija": "C",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": ""
          },
          {
            "Redni broj": "6.",
            "Kod": "OPB1012",
            "Naziv kolegija": "Engleski jezik 1",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr. sc. Ivana Grbavac,doc."
          },
          {
            "Redni broj": "7.",
            "Kod": "INB1071",
            "Naziv kolegija": "Tjelesna i zdravstvena kultura 1",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "1",
            "Nastavnik/asistent": "dr.sc. Ivan Kvesić, doc."
          },
          {
            "Redni broj": "8.",
            "Kod": "FFB1012",
            "Naziv kolegija": "Filozofija znanosti",
            "P": "15",
            "S": "0",
            "V": "30",
            "Status kolegija": "C",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr.sc. Zoran Primorac, red. prof."
          },
          {
            "Redni broj": "9.",
            "Kod": "PKB3052",
            "Naziv kolegija": "Novi mediji u odgoju i obrazovanju",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "B",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr. sc. Zoran Primorac, red. prof."
          },
    ],
    [
        {
            "Redni broj": "1.",
            "Kod": "INB2116",
            "Naziv kolegija": "Rješavanje problemskih zadataka programiranjem",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Goran Kraljević, doc. Emil Brajković.viši asistent"
          },
          {
            "Redni broj": "2.",
            "Kod": "INB2028",
            "Naziv kolegija": "Programiranje 2",
            "P": "30",
            "S": "30",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "8",
            "Nastavnik/asistent": "dr. sc.  Marko Rosić,  red. Prof. Krešimir Rakić, v.asist."
          },
          {
            "Redni broj": "3.",
            "Kod": "FIB2043",
            "Naziv kolegija": "Računalni praktikum 2",
            "P": "15",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "3",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc Hrvoje Ljubić. asistent"
          },
          {
            "Redni broj": "4.",
            "Kod": "INB2028",
            "Naziv kolegija": "Matematika 2",
            "P": "45",
            "S": "0",
            "V": "45",
            "Status kolegija": "A",
            "ECTS bodovi": "8",
            "Nastavnik/asistent": "dr. sc. Sanja Tipurić Spužević, doc. Mila Zovko, viši asistent"
          },
          {
            "Redni broj": "5.",
            "Kod": "OPB2092",
            "Naziv kolegija": "Strani jezik 2 (engleski)",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr.sc.Ivana Grbavac,doc."
          },
          {
            "Redni broj": "6.",
            "Kod": "OPB2031",
            "Naziv kolegija": "Tjelesna i zdravstvena kultura 2",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "1",
            "Nastavnik/asistent": "dr.sc. Ivan Kvesić, doc."
          },
          {
            "Redni broj": "7.",
            "Kod": "INB2132",
            "Naziv kolegija": "Informatički projekt 1",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc Hrvoje Ljubić. asistent"
          },
    ],
    [
        {
            "Redni broj": "1.",
            "Kod": "INB3056",
            "Naziv kolegija": "Primjenjena statistika",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Sanja Tipurić Spužević, doc Mila Zovko, viši asistent."
          },
          {
            "Redni broj": "2.",
            "Kod": "INB3026",
            "Naziv kolegija": "Modeliranje i simuliranje",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc. Miroslav Grubišić, doc."
          },
          {
            "Redni broj": "3.",
            "Kod": "INB3035",
            "Naziv kolegija": "Računalne mreže",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": "dr.sc. Drago Žagar, red.prof."
          },
          {
            "Redni broj": "4.",
            "Kod": "INB3042",
            "Naziv kolegija": "Praktikum Računalne mreže",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr.sc. Drago Žagar, red.prof."
          },
          {
            "Redni broj": "5.",
            "Kod": "INB3046",
            "Naziv kolegija": "Strukture podataka i algoritmi",
            "P": "30",
            "S": "15",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Marko Rosić, red. prof. Hrvoje Ljubić. asistent"
          },
          {
            "Redni broj": "6.",
            "Kod": "INB3044",
            "Naziv kolegija": "Baze podataka",
            "P": "15",
            "S": "0",
            "V": "15",
            "Status kolegija": "A",
            "ECTS bodovi": "4",
            "Nastavnik/asistent": "Dr. sc. Dražena Gašpar, red. prof. Daniel Vasić, viši asistent"
          },
          {
            "Redni broj": "7.",
            "Kod": "OPB3011",
            "Naziv kolegija": "Tjelesna i zdravstvena kultura 3",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "1",
            "Nastavnik/asistent": "dr.sc. Ivan Kvesić, doc."
          },
    ],
    [
        {
            "Redni broj": "1.",
            "Kod": "INB4092",
            "Naziv kolegija": "Informatički projekt Baze podataka",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "Dr. sc. Dražena Gašpar, red. prof. Daniel Vasić, viši asistent"
          },
          {
            "Redni broj": "2.",
            "Kod": "INB4026",
            "Naziv kolegija": "Arhitektura računala",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": "dr. sc.  Sven Gotovac. red. prof. dr. sc. Željko Marušić ,v.asist."
          },
          {
            "Redni broj": "3.",
            "Kod": "INB4095",
            "Naziv kolegija": "Kombinatorna i diskretna matematika",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": ""
          },
          {
            "Redni broj": "4.",
            "Kod": "INB4093",
            "Naziv kolegija": "Algoritmi u primjeni",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "4",
            "Nastavnik/asistent": "dr. sc.  Marko Rosić, red. prof. Hrvoje Ljubić. asistent"
          },
          {
            "Redni broj": "5.",
            "Kod": "INM3035",
            "Naziv kolegija": "Teorija informacija",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": "dr. sc. Irena Galić, doc. Daniel Vasić, v. asistent."
          },
          {
            "Redni broj": "6.",
            "Kod": "OPB4011",
            "Naziv kolegija": "Tjelesna i zdravstvena kultura 4",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "D",
            "ECTS bodovi": "1",
            "Nastavnik/asistent": "dr.sc. Ivan Kvesić, doc."
          },
          {
            "Redni broj": "7.",
            "Kod": "INB4096",
            "Naziv kolegija": " Objektno orijentirano programiranje",
            "P": "30",
            "S": "0",
            "V": "45",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Marko Rosić, red. prof. Daniel Vasić, viši asistent"
          },
          {
            "Redni broj": "8.",
            "Kod": "INB4082",
            "Naziv kolegija": "Informatički projekt 2",
            "P": "0",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc Hrvoje Ljubić. asistent"
          },
    ],
    [
        {
            "Redni broj": "1.",
            "Kod": "INM1065",
            "Naziv kolegija": "Numerička matematika",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": "Dr.sc. Bojan Crnković, izv.prof. Mila Zovko, v. asist."
          },
          {
            "Redni broj": "2.",
            "Kod": "INB5026",
            "Naziv kolegija": "Operacijski sustavi",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Sven Gotovac. red. prof. dr. sc. Željko Marušić ,v.asist."
          },
          {
            "Redni broj": "3.",
            "Kod": "INB5038",
            "Naziv kolegija": "	Programiranje za internet",
            "P": "30",
            "S": "0",
            "V": "45",
            "Status kolegija": "A",
            "ECTS bodovi": "8",
            "Nastavnik/asistent": "dr. sc. Tomislav Volarić, doc. Daniel Vasić, viši asistent"
          },
          {
            "Redni broj": "4.",
            "Kod": "INB5046",
            "Naziv kolegija": "Uvod u umjetnu inteligenciju",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc. Tomislav Volarić, doc. Hrvoje Ljubić, asistent"
          },
          {
            "Redni broj": "5.",
            "Kod": "",
            "Naziv kolegija": "Izborni kolegij",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "B",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": ""
          },
    ],
    [
        {
            "Redni broj": "1.",
            "Kod": "INB5036",
            "Naziv kolegija": "Paralelno programiranje",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr.sc. Željko Marušić, doc."
          },
          {
            "Redni broj": "2.",
            "Kod": "INB6026",
            "Naziv kolegija": "Programsko inženjerstvo",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc.  Branko Žitko, doc.Danijel Vasić,v. asist."
          },
          {
            "Redni broj": "3.",
            "Kod": "IN8046",
            "Naziv kolegija": "Završni rad",
            "P": "6",
            "S": "6",
            "V": "0",
            "Status kolegija": "A",
            "ECTS bodovi": "2",
            "Nastavnik/asistent": ""
          },
          {
            "Redni broj": "4.",
            "Kod": "INB6185",
            "Naziv kolegija": "Završni informatički projekt",
            "P": "0",
            "S": "30",
            "V": "30",
            "Status kolegija": "A",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": "dr. sc.  Tomislav Volarić, doc Hrvoje Ljubić. asistent"
          },
          {
            "Redni broj": "5.",
            "Kod": "INB6116",
            "Naziv kolegija": "Informatička praksa",
            "P": "",
            "S": "",
            "V": "",
            "Status kolegija": "A",
            "ECTS bodovi": "6",
            "Nastavnik/asistent": "dr. sc. Tomislav Volarić, doc. Daniel Vasić, v. asist."
          },
          {
            "Redni broj": "6.",
            "Kod": "",
            "Naziv kolegija": "Izborni kolegij",
            "P": "30",
            "S": "0",
            "V": "30",
            "Status kolegija": "B",
            "ECTS bodovi": "5",
            "Nastavnik/asistent": ""
          },
    ]
]